server:
  port: 80
  # servlet:
  #  context-path: /Shopme
spring:
  datasource:
    password: *****
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: *********
            client-secret: **********
            scope:
              - email
              - profile







